### ISSUE TITLE
Null terminator for LOAD_AND_LAUNCH_CUSTOM_MISSION (0A94)

### ISSUE THREAD

**Issue by JuniorDjjr** [thelink2012/vscode-gta3script#37]
`LOAD_AND_LAUNCH_CUSTOM_MISSION` doesn't add null terminator.

btw: a workaround while it's still not fixed:
```
LOAD_AND_LAUNCH_CUSTOM_MISSION "a"
DUMP
00
ENDDUMP
```

**Comment by thelink2012** [comment]
Moved to https://github.com/GTAmodding/gta3script-config/issues/1
