### ISSUE TITLE
How should we pass user parameters to $GTA3SC?

### ISSUE THREAD

**Issue by thelink2012** [thelink2012/vscode-gta3script#4]
A few options:

  + Use a comment at the very top of the script which this extension will detect and forward to $GTA3SC.
     - Cons: Would this be too `gta3sc` specific?
     - Cons: Would this be ugly and hacky?
  + Try to make a option menu or something.
     - Cons: The user will need to edit this menu each time it switch from a multifile script to e.g. a custom script.
      - Cons: Other users will not receive the proper compilation options!?!?
  + Use a e.g. `.xml` configuration file alongside the `.sc` file.
      - Ugh, this doesn't fit GTA3script!?

All of the current options are weird....

This is specially necessary for toggling CLEO and switching between game versions.

**Comment by ifarbod** [comment]
I would say the json/xml file is rather a better approach.

**Comment by thelink2012** [comment]
I think I've found a solution for that within VSCode itself :dagger:
